sudo: false
language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
    - "pypy"

cache:
    apt: true
    pip: true
    directories:
        - $HOME/download-cache

addons:
    apt_packages:
        - binutils
        - default-jdk
        - gdal-bin
        - libgdal1h
        - libgeos-c1
        - libproj-dev
        - libxapian22
        - python-xapian
        - wajig

before_install:
    - mkdir -p $HOME/download-cache

install:
    - pip install requests "Django${DJANGO_VERSION}"
    - python setup.py clean build install

before_script:
    - BACKGROUND_SOLR=true test_haystack/solr_tests/server/start-solr-test-server.sh

script:
    - python test_haystack/solr_tests/server/wait-for-solr
    - python setup.py test

env:
    matrix:
        - DJANGO_VERSION=">=1.6,<1.7"
        - DJANGO_VERSION=">=1.7,<1.8"
        - DJANGO_VERSION=">=1.8,<1.9"

matrix:
    allow_failures:
        - python: "pypy"

services:
    - elasticsearch

notifications:
    irc: "irc.freenode.org#haystack"
    email: false
