sudo: required
dist: bionic
language: python
python:
    - 3.5
    - 3.6
    - 3.7
    - pypy3
services:
    - docker

cache:
    apt: true
    pip: true
    directories:
        - $HOME/download-cache

addons:
    apt_packages:
        - binutils
        - openjdk-8-jdk
        - gdal-bin
        - libgdal20
        - libgeos-c1v5
        - libproj-dev
        - python-xapian
        - wajig

before_install:
    - mkdir -p $HOME/download-cache
    - >
        if [[ $VERSION_ES == '>=2.0.0,<3.0.0' ]];
        then
          docker run -d -p 9200:9200 elasticsearch:2.4.6-alpine
        elif [[ $VERSION_ES == '>=5.0.0,<6.0.0' ]];
        then
          docker run -d -p 9200:9200 elasticsearch:5.6.10-alpine
        else
          docker run -d -p 9200:9200 elasticsearch:1.7.6-alpine
        fi

install:
    - pip install --upgrade setuptools
    - pip install codecov coverage
    - pip install requests "Django${DJANGO_VERSION}" "elasticsearch${VERSION_ES}"
    - python setup.py clean build install

before_script:
    - BACKGROUND_SOLR=true test_haystack/solr_tests/server/start-solr-test-server.sh

script:
    - python test_haystack/solr_tests/server/wait-for-solr
    - coverage run setup.py test

after_success:
    - codecov

env:
    global:
        - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
    matrix:
        - DJANGO_VERSION=">=1.11,<2.0" VERSION_ES=">=1.0.0,<2.0.0"
        - DJANGO_VERSION=">=2.0,<2.1" VERSION_ES=">=1.0.0,<2.0.0"
        - DJANGO_VERSION=">=2.1,<2.2" VERSION_ES=">=1.0.0,<2.0.0"
        - DJANGO_VERSION=">=1.11,<2.0" VERSION_ES=">=2.0.0,<3.0.0"
        - DJANGO_VERSION=">=2.0,<2.1" VERSION_ES=">=2.0.0,<3.0.0"
        - DJANGO_VERSION=">=2.1,<2.2" VERSION_ES=">=2.0.0,<3.0.0"
        - DJANGO_VERSION=">=1.11,<2.0" VERSION_ES=">=5.0.0,<6.0.0"
        - DJANGO_VERSION=">=2.0,<2.1" VERSION_ES=">=5.0.0,<6.0.0"
        - DJANGO_VERSION=">=2.1,<2.2" VERSION_ES=">=5.0.0,<6.0.0"
matrix:
    allow_failures:
        - python: 'pypy3'
    exclude:
        - python: pypy3
          env: DJANGO_VERSION=">=2.0,<2.1" VERSION_ES=">=5.0.0,<6.0.0"
        - python: pypy3
          env: DJANGO_VERSION=">=2.0,<2.1" VERSION_ES=">=2.0.0,<3.0.0"
        - python: pypy3
          env: DJANGO_VERSION=">=2.0,<2.1" VERSION_ES=">=1.0.0,<2.0.0"
        - python: pypy3
          env: DJANGO_VERSION=">=2.1,<2.2" VERSION_ES=">=5.0.0,<6.0.0"
        - python: pypy3
          env: DJANGO_VERSION=">=2.1,<2.2" VERSION_ES=">=2.0.0,<3.0.0"
        - python: pypy3
          env: DJANGO_VERSION=">=2.1,<2.2" VERSION_ES=">=1.0.0,<2.0.0"

notifications:
    irc: 'irc.freenode.org#haystack'
    email: false
